[build]
builder = "nixpacks"
sourceDir = "backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/chat/start"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Environment variables can be set here
[variables]
NODE_ENV = "production" 